disable-custom-skins: false
disable-custom-capes: true
disable-custom-geometry: true
disable-ingame-skin-change: true
disable-transparent-skins: true
allowed-transparency-percentage: 5
# Recommended minimum percentage for slim skins: 4
# Set the percentage to 0 to prohibit transparency in the base skin.
